version: '2'
services:
    microservice2-mysql:
        container_name: microservice2-mysql
        image: mysql:5.7.14
        # volumes:
        #     - ~/volumes/jhipster/microservice2/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=microservice2
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
